meta_product_name: "Enchoosiast"
meta_title: "Enchoosiast - Find, change and revolutionize your career path."
meta_description: "Find, change and revolutionize your career path."
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
